trigger:
  branches:
    include:
      - main   # Trigger when a commit is pushed to 'main'.

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based hosted agent.

parameters:
  - name: appName
    type: string
    default: 'SRE'
  - name: environment
    type: string
    default: 'LAB'
  - name: region
    type: string
    default: 'eastus'
  - name: subscriptionId
    type: string
    default: '3c42e4b1-a438-4481-8bc2-25a884892a68'  # Replace with your valid subscription ID.

variables:
  azureServiceConnection: 'SC-KYLEBICEPTESTING'  # Your Azure service connection name.

steps:
  # Task 1: Deploy Resource Groups using the rg-deployment.bicep template.
  - task: AzureCLI@2
    displayName: 'Deploy Resource Groups'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Setting subscription context..."
        az account set --subscription "${{ parameters.subscriptionId }}"
        echo "Deploying resource groups..."
        az deployment sub create \
          --location "${{ parameters.region }}" \
          --template-file "$(System.DefaultWorkingDirectory)/infra/modules/rg-deployment.bicep" \
          --parameters backupRGName="rg-${{ parameters.appName }}-${{ parameters.environment }}-ortig-backup" region="${{ parameters.region }}"

  # Task 2: Deploy Child Resources into the Backup Resource Group.
  - task: AzureCLI@2
    displayName: 'Deploy Child Resources'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Deploying child resources into backup resource group..."
        az deployment group create \
          --resource-group "rg-${{ parameters.appName }}-${{ parameters.environment }}-ortig-backup" \
          --template-file "$(System.DefaultWorkingDirectory)/infra/modules/child-resources.bicep" \
          --parameters appName="${{ parameters.appName }}" environment="${{ parameters.environment }}" region="${{ parameters.region }}"

  # Task 3: Deploy the Backup Vault (ABV) into the Backup Resource Group.
  - task: AzureCLI@2
    displayName: 'Deploy Backup Vault (ABV)'
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Deploying Backup Vault (ABV)..."
        az deployment group create \
          --resource-group "rg-${{ parameters.appName }}-${{ parameters.environment }}-ortig-backup" \
          --template-file "$(System.DefaultWorkingDirectory)/infra/modules/abv-deployment.bicep" \
          --parameters appName="${{ parameters.appName }}" environment="${{ parameters.environment }}" region="${{ parameters.region }}"
